name: stagexl_chess_pieces
description: A package for StageXL that lets developers add high quality vector chess pieces to their project.

version: 1.0.0
author: Mark Tanner <admin@64bitdragon.com>
homepage: https://github.com/marktanner1331/StageXL-Vector-Chess-Pieces

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  stagexl: ^1.1.0
